import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { validateIcon } from "./validate-icon.mjs";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const catalog = join(packageRoot, "icons");
const output = join(packageRoot, "src", "icons.generated.ts");
const check = process.argv.includes("--check");
const files = readdirSync(catalog).filter((name) => name.endsWith(".svg")).sort();
if (!files.length) throw new Error("Icon catalog is empty");

const icons = files.map((file) => {
  const name = file.slice(0, -4);
  if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(file + ": invalid icon name");
  return [name, validateIcon(file, readFileSync(join(catalog, file), "utf8"))];
});
const names = icons.map(([name]) => name);
const generated = [
  "/* Generated by scripts/sync-icons.mjs. Edit icons/*.svg, then run pnpm icons:sync. */",
  "export const WL_ICON_NAMES = " + JSON.stringify(names, null, 2) + " as const;",
  "export type WlIconName = typeof WL_ICON_NAMES[number];",
  "export const WL_ICONS: Record<WlIconName, string> = {",
  ...icons.map(([name, body]) => "  " + JSON.stringify(name) + ": " + JSON.stringify(body) + ","),
  "};",
  ""
].join("\n");
if (check) {
  if (readFileSync(output, "utf8") !== generated) throw new Error("Icon registry is stale; run pnpm icons:sync");
  console.log("Icon catalog verified: " + names.length + " icons");
} else {
  writeFileSync(output, generated);
  console.log("Generated " + names.length + " icons");
}
