name: Ошибка
description: Сообщить об ошибке и показать, как её повторить
title: "[Bug]: "
body:
  - type: input
    id: gavia
    attributes:
      label: Версия Gavia UI
      placeholder: "0.11.0"
    validations:
      required: true
  - type: input
    id: vue
    attributes:
      label: Версия Vue
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Браузер, версия и ОС
    validations:
      required: true
  - type: dropdown
    id: theme
    attributes:
      label: Тема
      options:
        - Gavia
        - Gavia Dark
        - Classic
        - Classic Dark
        - Newspaper
        - Собственная
  - type: textarea
    id: reproduction
    attributes:
      label: Как повторить ошибку?
      description: Дайте ссылку на небольшой пример или приложите Vue SFC и опишите шаги. Уберите секреты и данные пользователей.
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Что ожидали и что произошло?
    validations:
      required: true

