name: Предложение
description: Предложить улучшение Gavia UI
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу нужно решить?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Как должно работать?
      description: Опишите поведение и приведите пример использования.
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: Что важно сохранить и какие варианты уже пробовали?

