import { russianPlaygroundUrl } from "./playground-url";
import { expect, test, type Page } from "@playwright/test";

function docsUrl(baseURL: string | undefined, component: string): string {
  const url = new URL(baseURL ?? "http://127.0.0.1:4173/");
  url.search = "?view=docs&component=" + component;
  url.hash = "";
  return url.href;
}
const errors = new WeakMap<Page, string[]>();
test.beforeEach(async ({ page }) => {
  const messages: string[] = [];
  errors.set(page, messages);
  page.on("pageerror", (error) => messages.push(error.message));
});
test.afterEach(async ({ page }) => { expect(errors.get(page), "Input documentation has no runtime errors").toEqual([]); });

test("checkbox documentation demonstrates a real mixed group, labels, validation and disabled state", async ({ page, baseURL }) => {
  await page.goto(russianPlaygroundUrl(docsUrl(baseURL, "WlCheckbox")), { waitUntil: "domcontentloaded" });
  const example = page.locator('[data-input-example="WlCheckbox"]');
  await expect(example).toBeVisible();
  const parent = example.getByRole("checkbox", { name: "Все доступные уведомления", exact: true });
  await expect.poll(() => parent.evaluate((node) => (node as HTMLInputElement).indeterminate)).toBe(true);
  await parent.press("Space");
  await expect(example.getByRole("checkbox", { name: "Письма", exact: true })).toBeChecked();
  const push = example.getByRole("checkbox", { name: "Push-уведомления", exact: true });
  await expect(push).toBeChecked();
  await expect.poll(() => parent.evaluate((node) => (node as HTMLInputElement).indeterminate)).toBe(false);
  await push.uncheck();
  await expect.poll(() => parent.evaluate((node) => (node as HTMLInputElement).indeterminate)).toBe(true);
  const consent = example.getByRole("checkbox", { name: "Согласен с условиями", exact: true });
  await expect(consent).toHaveAttribute("aria-invalid", "true");
  await expect(consent).toHaveAttribute("aria-describedby", "docs-checkbox-consent-desc");
  await consent.check();
  await expect(example.getByRole("alert")).toHaveCount(0);
  await expect(consent).not.toHaveAttribute("aria-invalid", "true");
  const mandatory = example.getByRole("checkbox", { name: "Системные уведомления обязательны", exact: true });
  await expect(mandatory).toBeDisabled();
  await expect(mandatory).toBeChecked();
  await example.getByRole("button", { name: "Снять доступные флажки", exact: true }).click();
  await expect(parent).not.toBeChecked();
  await expect(mandatory).toBeChecked();
  await expect(example.getByRole("status")).toContainText("Выбрано уведомлений: 0 из 2");
});

test("multiselect documentation filters and selects with the keyboard, removes chips and clears its model", async ({ page, baseURL }) => {
  await page.goto(russianPlaygroundUrl(docsUrl(baseURL, "WlMultiSelect")), { waitUntil: "domcontentloaded" });
  const example = page.locator('[data-input-example="WlMultiSelect"]');
  await expect(example).toBeVisible();
  const control = example.getByRole("combobox", { name: "Направления с фильтром", exact: true });
  await control.press("ArrowDown");
  await expect(control).toHaveAttribute("aria-expanded", "true");
  const filter = page.getByRole("searchbox", { name: "Фильтр", exact: true });
  await filter.fill("Документация");
  await expect(page.getByRole("listbox").getByRole("option")).toHaveCount(1);
  await filter.press("Home");
  await filter.press("Enter");
  await expect(example.getByRole("status")).toContainText("Выбрано: 3");
  await expect(control).toHaveAttribute("aria-expanded", "true");
  await control.press("Escape");
  await expect(control).toHaveAttribute("aria-expanded", "false");
  await example.getByRole("button", { name: "Удалить Документация", exact: true }).click();
  await expect(example.getByRole("status")).toContainText("Выбрано: 2");
  await example.getByRole("button", { name: "Очистить направления", exact: true }).click();
  await expect(example.getByRole("status")).toContainText("Выбрано: 0");
  await expect(example.getByRole("combobox", { name: "Не менее одного направления", exact: true })).toHaveAttribute("aria-invalid", "true");
  await expect(example.getByText("Выберите хотя бы одно направление.", { exact: true })).toBeVisible();
  await expect(example.getByRole("combobox", { name: "Недоступный мультивыбор", exact: true })).toBeDisabled();
});

test("file documentation preserves cancelled batches and enforces local upload rejection, removal and replacement", async ({ page, baseURL }) => {
  await page.goto(russianPlaygroundUrl(docsUrl(baseURL, "WlFilePicker")), { waitUntil: "domcontentloaded" });
  const picker = page.locator('[data-input-example="WlFilePicker"]');
  await expect(picker).toBeVisible();
  const input = picker.locator('input[type="file"]').first();
  const batch = [{ name: "notes.txt", mimeType: "text/plain", buffer: Buffer.from("Notes") }, { name: "agenda.txt", mimeType: "text/plain", buffer: Buffer.from("Agenda") }];
  await input.setInputFiles(batch);
  await expect(picker.getByRole("status")).toContainText("Документов: 2");
  await expect(input).toHaveValue("");
  await input.dispatchEvent("cancel");
  await expect(picker.getByRole("status")).toContainText("Выбор отменён. Прежний список файлов сохранён");
  await expect(picker.getByRole("listitem")).toHaveCount(2);
  await input.setInputFiles(batch);
  await expect(picker.getByRole("status")).toContainText("Выбрано файлов: 2");
  await expect(picker.getByRole("listitem")).toHaveCount(2);
  await expect(picker.getByRole("button", { name: "Недоступный выбор", exact: true })).toBeDisabled();
  await picker.getByRole("button", { name: "Очистить файлы", exact: true }).click();
  await expect(picker.getByRole("listitem")).toHaveCount(0);
  await expect(picker.getByRole("status")).toContainText("Документов: 0");

  await page.goto(russianPlaygroundUrl(docsUrl(baseURL, "WlFileUpload")), { waitUntil: "domcontentloaded" });
  const upload = page.locator('[data-input-example="WlFileUpload"]');
  await expect(upload).toBeVisible();
  const documents = upload.getByRole("region", { name: "Документы: тип, размер и количество", exact: true });
  const docsInput = documents.locator('input[type="file"]');
  await docsInput.setInputFiles([...batch, { name: "unsafe.exe", mimeType: "application/octet-stream", buffer: Buffer.from("Rejected") }]);
  await expect(upload.getByRole("status")).toContainText("Документов: 2");
  await expect(documents.getByRole("alert")).toContainText("тип файла не поддерживается");
  await docsInput.setInputFiles({ name: "third.txt", mimeType: "text/plain", buffer: Buffer.from("Third") });
  await expect(documents.getByRole("alert")).toContainText("лимит файлов: 2");
  await documents.getByRole("button", { name: "Удалить notes.txt", exact: true }).click();
  await expect(upload.getByRole("status")).toContainText("Документов: 1");
  await docsInput.setInputFiles({ name: "third.txt", mimeType: "text/plain", buffer: Buffer.from("Third") });
  await expect(upload.getByRole("status")).toContainText("Документов: 2");
  await docsInput.dispatchEvent("cancel");
  await expect(documents.getByRole("button", { name: "Удалить third.txt", exact: true })).toBeVisible();
  const images = upload.getByRole("region", { name: "Один файл заменяет предыдущий", exact: true });
  const imageInput = images.locator('input[type="file"]');
  await imageInput.setInputFiles({ name: "first.png", mimeType: "image/png", buffer: Buffer.from("First image payload") });
  await imageInput.setInputFiles({ name: "second.png", mimeType: "image/png", buffer: Buffer.from("Second image payload") });
  await expect(images.getByRole("button", { name: "Удалить first.png", exact: true })).toHaveCount(0);
  await expect(images.getByRole("button", { name: "Удалить second.png", exact: true })).toBeVisible();
  await expect(upload.getByRole("status")).toContainText("Изображений: 1");
  await upload.getByRole("button", { name: "Очистить списки и ошибки", exact: true }).click();
  await expect(upload.getByRole("alert")).toHaveCount(0);
  await expect(upload.getByRole("status")).toHaveText("Документов: 0. Изображений: 0.");
});
test("autocomplete object examples preserve typed text, update complete suggestions and select objects", async ({ page, baseURL }) => {
  await page.goto(russianPlaygroundUrl(docsUrl(baseURL, "WlAutocomplete")), { waitUntil: "domcontentloaded" });
  const example = page.locator('[data-input-example="WlAutocomplete"]');
  await expect(example).toBeVisible();
  const control = example.getByRole("combobox", { name: "Ответственный", exact: true });
  await control.fill("Дми");
  await expect(control).toHaveValue("Дми");
  const list = page.getByRole("listbox");
  await expect(list.getByRole("option")).toHaveCount(1);
  await expect(list.getByRole("option", { name: "Дмитрий", exact: true })).toBeVisible();
  await control.press("Home");
  await control.press("Enter");
  await expect(control).toHaveValue("Дмитрий");
  await expect(example.getByRole("status")).toContainText("Ответственный: Дмитрий");
  await example.getByRole("button", { name: "Показать участников", exact: true }).click();
  await page.getByRole("listbox").getByRole("option", { name: "Елена", exact: true }).click();
  await expect(example.getByRole("status")).toContainText("Участники: Анна, Елена");
  await expect(example.getByRole("button", { name: "Удалить Елена", exact: true })).toBeVisible();
  await example.getByRole("button", { name: "Очистить выбранные значения", exact: true }).click();
  await expect(control).toHaveValue("");
  await expect(example.getByRole("status")).toHaveText("Ответственный: не выбран. Участники: не выбраны.");
  await expect(example.getByRole("button", { name: "Удалить Елена", exact: true })).toHaveCount(0);
});